apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "jupyter-with-spark.fullname" . }}
  labels:
    app: {{ template "jupyter-with-spark.name" . }}
    chart: {{ template "jupyter-with-spark.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "jupyter-with-spark.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jupyter-with-spark.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.jupyterService.port }}
              protocol: TCP
            - name: web-ui
              containerPort: {{ .Values.sparkWebUI.port }}
              protocol: TCP
          command:
            - "/bin/sh"
            - "-c"
            - >
              jupyter notebook --generate-config;
              size=$(wc -c < /tmp/conf/jupyter/jupyter_notebook_config.py)
              if [ $size -gt 0 ]; then cp /tmp/conf/jupyter/jupyter_notebook_config.py /home/jovyan/.jupyter/jupyter_notebook_config.py; fi;
            {{- if eq .Values.jupyterService.password "false" }}
              . /usr/local/bin/start.sh jupyter notebook --NotebookApp.token='' --NotebookApp.port={{ .Values.jupyterService.port }}
            {{ else }}
              echo "{ \"NotebookApp\": { \"password\": \"REPLACE_ME\" } }" > ~/.jupyter/jupyter_notebook_config.json;
              printf "import os\nfrom notebook.auth import passwd\nprint(passwd('{{ .Values.jupyterService.password }}'))" > hash.py;
              export HASHED=`python hash.py`;
              rm -rf hash.py;
              sed -i -e "s/REPLACE_ME/${HASHED}/g" ~/.jupyter/jupyter_notebook_config.json;
              . /usr/local/bin/start.sh jupyter notebook --NotebookApp.port={{ .Values.jupyterService.port }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: jupyter-config
            mountPath: /tmp/conf/jupyter/
          - name: spark-config
            mountPath: /opt/spark/conf/
#            mountPath: /tmp/conf/spark/ # TODO Update image. /opt/spark is currently not writable by non-root user jovyan.
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      serviceAccount: {{ .Values.serviceAccount }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: jupyter-config
          configMap:
            name: {{ .Release.Name }}-jupyter-configmap
        - name: spark-config
          configMap:
            name: {{ .Release.Name }}-spark-configmap
